branch-defaults:
  main:
    environment: Testcirclecicdnode-env-2
global:
  application_name: test-circlecicd-node
  default_platform: Node.js 12 running on 64bit Amazon Linux 2/5.4.5
  default_region: ap-northeast-1
  sc: git